### ISSUE TITLE
v1 roadmap

### ISSUE THREAD

**Issue by anyweez** [anyweez/newsy#3]
- [x] Extract broad list of countries using keywords
- [ ] Label several hundred per country (top x countries, maybe?)
- [x] Basic tools for measuring accuracy, coverage, etc
- [ ] Basic tools for measuring source quality (# of stories, extractable text, etc)
- [x] Generate country-heatmap mapping
- [x] Render heatmap on webpage (#4)
- [x] Retrieve articles per-country to display (#10)
- [x] Display articles in sliding window (#13)

**Comment by anyweez** [comment]
Live deployment of worldview is available here: https://anyweez.github.io/newsy.io/. Currently not updating content on a regular basis though it should be relatively straightforward to do with cron.
